Feature: implement timeseries #4 #28
rl-institut/simbev pull request #35
Opened 2021-07-26 11:27 UTC by Tk1999s

included midtimeseries in simbev, so that simulations over more than 14 days are possible.

this PR closes #4 
and closes #28

2021-07-28 11:37 UTC, nesnoj commented
Thanks for this super nice feature! I agreed with @khelfen that he'll do the review...

2021-07-30 08:58 UTC, khelfen requested changes
@Tk1999s Please add the `__pychache__` into the `.gitignore` file and remove those binary files from the PR. Also I added some small remarks but nothing big.

2021-07-30 08:58 UTC, khelfen commented on simbev/mid_timeseries.py
> +    elif date.month <= 5: season = "Fruehling"
it's okay, but for me it's weird to have the `if` and the `TODO` in one line

2021-07-30 08:58 UTC, khelfen commented on simbev/mid_timeseries.py
> +cutoff_dates = (3, 6, 9, 12)
better add hard coded variables into the config files and load them into the script

2021-07-30 08:58 UTC, khelfen commented on simbev/mid_timeseries.py
> +    weekday = 7
better add hard coded variables into the config files

2021-07-30 08:58 UTC, khelfen commented on simbev/main_simbev.py
> +    region_path.mkdir(exist_ok=True)
I prefare `os.makedirs()` over `path.mkdir()`. See [this](https://stackoverflow.com/a/13819575/13491957) answer on SO.

2021-07-30 08:58 UTC, khelfen commented on simbev/main_simbev.py
> +             work_charging_capacity) = simbevMiD.availability(
we really need to refactor this function :joy:

2021-08-10 08:28 UTC, khelfen approved these changes

2021-08-10 08:30 UTC, khelfen commented
looks fine :) I can't merge it tough as I don't have the rights :sweat_smile:

2021-08-24 11:56 UTC, merged